### ISSUE TITLE
[Question/ Enhancement] Possibility to dilate a geometry?

### ISSUE THREAD

**Issue by JohnDemand** [mattools/matGeom#127]
Is it possible with matGeom to buffer/ dilate an object by a given distance?

Im thinking of something similar to this feature from a Python Module called shapely: 
>  `object.buffer(distance, resolution=16, cap_style=1, join_style=1, mitre_limit=5.0, single_sided=False)`
Returns an approximate representation of all points within a given distance of the this geometric object.
https://shapely.readthedocs.io/en/stable/manual.html#object.buffer
![](https://shapely.readthedocs.io/en/stable/_images/buffer.png)

Regards,
John

**Comment by dlegland** [comment]
Hi,
There is a function with rather similar output: expandPolygon. It can be seen as a simplified buffer computation (limited to polygons, no management of join options, algorithmic complexity not optimized...)

otherwise, there is ne generic appraoch for buffer / offset computation of geometric shapes in general.

**Comment by JohnDemand** [comment]
Thank you for the quick response! 
I guess it will be expandPolygon then.
