### ISSUE TITLE
drawArrow.m why  axis equal?

### ISSUE THREAD

**Issue by stoneFriable999** [mattools/matGeom#194]
Hello,

Why in drawArrow.m at line 101 is there "axis equal"? It messes up my plots and I have to comment it.

thanks

**Comment by oqilipo** [comment]
You might remove it and create a pull request?

**Comment by dlegland** [comment]
Hi,
the readon was to ensure the two sides of the arrow had symmetric aspect. When changing axis aspect ratio this is no longer true.
But I am ok to remove the "axis equal" command, and let the user adjust according to preference.
If you can create a PR that 's great. Otherwise we can have a look;

David

**Comment by stoneFriable999** [comment]
Hello,

I will, thank you very much for your work.

best
